import { Montserrat } from 'next/font/google';
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "BolehNgopi - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
